SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS BS
WHERE 1=1
      AND B.BOOK_ID = BS.BOOK_ID
      AND B.AUTHOR_ID = A.AUTHOR_ID
      AND SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC;