SELECT ANIMAL_ID, NAME
FROM
(
    SELECT B.ANIMAL_ID, B.NAME, DATEDIFF(B.DATETIME,A.DATETIME) AS 보호기간
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID
) C
ORDER BY 보호기간 DESC
LIMIT 2;