SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI, REST_REVIEW AS RR
WHERE 1=1
      AND RI.REST_ID = RR.REST_ID
      AND ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID, REST_NAME, FOOD_TYPE
ORDER BY SCORE DESC, FAVORITES DESC;