SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(AMOUNT)*PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS FO, FOOD_PRODUCT AS FP
WHERE 1=1 
     AND FO.PRODUCT_ID = FP.PRODUCT_ID
     AND PRODUCE_DATE LIKE '2022-05%'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID;
