# SELECT FLAVOR
# FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
#         FROM(
#             SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
#             FROM JULY
#             GROUP BY FLAVOR
#             UNION ALL
#             SELECT FLAVOR, TOTAL_ORDER
#             FROM FIRST_HALF
#             ) IMSI
#         GROUP BY FLAVOR
#         ORDER BY TOTAL_ORDER DESC
#       ) TOTAL
# LIMIT 3;

SELECT FLAVOR
FROM(
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        ) IMSI
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;