SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE 1=1
      AND A.PT_NO = P.PT_NO
      AND A.MDDR_ID = D.DR_ID
      AND APNT_YMD LIKE '2022-04-13%'
      AND APNT_CNCL_YN = 'N'
      AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;