SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB, USED_GOODS_USER UU
WHERE 1=1
      AND UB.WRITER_ID = UU.USER_ID
      AND STATUS = 'DONE'
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;
      