SELECT CH.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
WHERE 1=1
      AND C.CAR_ID = CH.CAR_ID
      AND MONTH(START_DATE) = 10
      AND CAR_TYPE = '세단'
GROUP BY CH.CAR_ID
ORDER BY CH.CAR_ID DESC;

