SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES BS
WHERE 1=1
      AND B.BOOK_ID = BS.BOOK_ID
      AND YEAR(SALES_DATE) = 2022
      AND MONTH(SALES_DATE) = 01
GROUP BY CATEGORY
ORDER BY CATEGORY;
